version: '3.8'

services:
  tienda_usuarios:
    build:
      context: ./Tienda_Usuarios
      dockerfile: Dockerfile
    container_name: tienda_usuarios_backend
    restart: always
    networks:
      - tienda_network
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # Variables para CORS y Seguridad
      - ALLOWED_ORIGINS=*
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=https://DCNGP6.b2clogin.com/DCNGP6.onmicrosoft.com/B2C_1_DCNGP6_LOGIN/discovery/v2.0/keys
      # Variables para Logging
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_CORS=DEBUG

  tienda_productos:
    build:
      context: ./Tienda_Productos
      dockerfile: Dockerfile
    container_name: tienda_productos_backend
    restart: always
    networks:
      - tienda_network
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # Variables para CORS y Seguridad
      - ALLOWED_ORIGINS=*
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=https://DCNGP6.b2clogin.com/DCNGP6.onmicrosoft.com/B2C_1_DCNGP6_LOGIN/discovery/v2.0/keys
      # Variables para Logging
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_CORS=DEBUG

  tienda_ordenes:
    build:
      context: ./Tienda_Ordenes
      dockerfile: Dockerfile
    container_name: tienda_ordenes_backend
    restart: always
    networks:
      - tienda_network
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # Variables para CORS y Seguridad
      - ALLOWED_ORIGINS=*
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=https://DCNGP6.b2clogin.com/DCNGP6.onmicrosoft.com/B2C_1_DCNGP6_LOGIN/discovery/v2.0/keys
      # Variables para Logging
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_CORS=DEBUG

  # tienda_web:
  #   build:
  #     context: ./Tienda
  #     dockerfile: Dockerfile
  #   container_name: tienda-web
  #   restart: always
  #   networks:
  #     - tienda_network
  #   ports:
  #     - "8080:80"

networks:
  tienda_network:
    name: CLOUD_NATIVE_I
    driver: bridge